### ISSUE TITLE
I can't connect to vcXsrv server

### ISSUE THREAD

**Issue by adonese** [aseering/wsl_gui_autoinstall#4]
While I'm able to use Xming server quite well, your script doesn't seem to work. I've followed the instructions, but when I run `bash --login` and issued a gui command such as emacs it still show in the bash, not from the server. I don't have a problem to keep using Xming, but I just want to try out yours :D, also curious to know the reason behind this error.

**Comment by aseering** [comment]
Hi @adonese , thanks for the report!  Hm...  Could you check two things?:
- Is VcXsrv running?  It should show up on the right side of the Taskbar with an "X" icon, same as Xming.
- If you run `echo $DISPLAY` in bash, what does it print?

**Comment by adonese** [comment]
VcXrsv isn't running actually. I don't know why, I saw it downloading from sourceforge. 
It displays `localhost:0`

Is there any advantage of VcXrsv over xming?

I could've downloaded it from sourceforge, but I'm interested more to know why it's not working. I guess I'll download it and stop my curiosity.

**Comment by aseering** [comment]
The free version of Xming was last updated in 2007.  It's a old version of X.  Most notably, it has no support for graphics acceleration; as a result, Unity (probably among other programs) doesn't work with it.

VcXsrv is updated much more regularly; the most-recent release was built at the end of June.  Current releases (1.18.x) are based on the same version of xorg as Ubuntu Xenial.  Ubuntu Trusty (the version used by WSL) is based on xorg 1.15; you can download that too, though my script just gets the new version.

**Comment by aseering** [comment]
If you're willing to debug a little bit more, I'd really appreciate it (so I can fix the script for other people too).  Two other questions:
- Do you have a "VcXsrv" link in your Startup folder?  (For me, that's `C:\Users\<username>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\`.)  If you double-click on it, does it launch VcXsrv?
- If not:  Do you have VcXsrv in your Start menu?  If you run it from there, does it start and work properly?

**Comment by adonese** [comment]
VcXsrv wasn't actually installed from your script, I guess that because my country is blocked by US. But when I used a vpn service for the the second time it was downloaded (about 48 mb or so). I guess it's an abnormal issue! BTW VcXsrv Is away better than Xming version!

Thank you aseering, again :+1:
