### ISSUE TITLE
update ubuntu package for xenail?

### ISSUE THREAD

**Issue by ericfont** [aseering/wsl_gui_autoinstall#6]
I'd like to update my WSL image to Xenail.  But I see your custom pulse audio package is only for Trusty.

**Comment by aseering** [comment]
Thanks @ericfont for posting -- actually, my custom pulse package is just a backport of the package that comes with Xenial.  So in theory, if you upgrade, in theory you shouldn't need my package any more.

If you do upgrade, let me know if the regular official package works for you.  If not, I can try to look into what's wrong.

**Comment by ericfont** [comment]
I upgraded (starting from a fresh WSL image of Trusty), and then apt-get install pulseaudio, but then when I try to paplay a wav file, I get:

<pre>
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
</pre>

I haven't tried anything else yet.  Should I rerun or modify any of the commands from your .bat file?

**Comment by ericfont** [comment]
Actually I got it working on Xenail by following https://github.com/Microsoft/BashOnWindows/issues/486#issuecomment-234930031 instructions to build pulseaudio with the special configure.

**Comment by aseering** [comment]
@ericfont -- interesting; glad you figured it out!  I can try to post updated packages, but I don't run Xenial on my own WSL machine.  I'm hoping that the WSL folks will release a bunch of socket updates / added support soon, before too many people make the jump to Xenial, so Xenial's stock pulseaudio works.
